services:
  db:
    image: postgres:17-alpine
    container_name: zenit-finance-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: zenit_finance
    volumes:
      - zenit_data:/var/lib/postgresql/data

volumes:
  zenit_data:
